version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: yarn start:dev
    restart: always

  pg-admin:
    container_name: pgadmin
    image: dpage/padmin4    
    restart: always
    environment:
     PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
     PGADMIN_DEFAULT_PASSWORD: 1234

    ports:
      - "5050:80"

  
      
